server:
  port: 8090
  servlet:
    contextPath: /blog
spring:
  application:
    name: blog-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc.lob.non_contextual_creation: true
    generate-ddl: true
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/blogs
    driverClassName: org.postgresql.Driver
logging:
  file: logs/blogging-service.log
  level:
    org.hibernate.SQL: ERROR
    org.springframework.data: DEBUG
